// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

var (
	Q     = new(Query)
	Admin *admin
	Node  *node
	Role  *role
)

func SetDefault(db *gorm.DB) {
	*Q = *Use(db)
	Admin = &Q.Admin
	Node = &Q.Node
	Role = &Q.Role
}

func Use(db *gorm.DB) *Query {
	return &Query{
		db:    db,
		Admin: newAdmin(db),
		Node:  newNode(db),
		Role:  newRole(db),
	}
}

type Query struct {
	db *gorm.DB

	Admin admin
	Node  node
	Role  role
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:    db,
		Admin: q.Admin.clone(db),
		Node:  q.Node.clone(db),
		Role:  q.Role.clone(db),
	}
}

type queryCtx struct {
	Admin IAdminDo
	Node  INodeDo
	Role  IRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin: q.Admin.WithContext(ctx),
		Node:  q.Node.WithContext(ctx),
		Role:  q.Role.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	return &QueryTx{q.clone(q.db.Begin(opts...))}
}

type QueryTx struct{ *Query }

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
