// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRoleNode = "role_node"

// RoleNode mapped from table <role_node>
type RoleNode struct {
	RoleNodeID int32 `gorm:"column:role_node_id;type:int(11);primaryKey;autoIncrement:true" json:"role_node_id"`
	RoleID     int32 `gorm:"column:role_id;type:int(11);not null" json:"role_id"` // 角色ID
	NodeID     int32 `gorm:"column:node_id;type:int(11);not null" json:"node_id"` // 节点ID
}

// TableName RoleNode's table name
func (*RoleNode) TableName() string {
	return TableNameRoleNode
}
